[pytest]
addopts = --alluredir=allure-results --clean-alluredir -v -p no:warnings

testpaths = tests

markers =
    ui: UI tests
    api: API tests
    hybrid: hybrid tests
    smoke: Critical tests
    flaky: Restarting unstable tests

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

norecursedirs = venv .git .pytest_cache
